server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: spring-saas
  profiles:
    active: dev
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Mail Configuration
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# CORS Configuration
cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.springsaas: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO 