server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: spring-saas
  profiles:
    active: dev
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Mail Configuration
  mail:
    host: mail.i-team.ma
    port: 587
    username: 
    password: 
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: 
          timeout: 30000
          connectiontimeout: 30000
          writetimeout: 30000
        transport:
          protocol: smtp
        debug: true

# Application Configuration
app:
  name: "SaaS Platform"
  frontend-url: "http://localhost:4200"
  email:
    from-name: "SaaS Platform"
    support-email: "report@i-team.ma"

# CORS Configuration
cors:
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

# Logging Configuration
logging:
  level:
    root: INFO
    com.example.springsaas: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.mail: DEBUG
    org.thymeleaf: DEBUG 
